const actionType = {
  SET_USERS: 'SET_USERS',
  CLEAR_USERS: 'CLEAR_USERS',
  SET_USER_FILTER: 'SET_USER_FILTER',

  SET_USER_CONTACT: 'SET_USER_CONTACT',
  CLEAR_USER_CONTACT: 'CLEAR_USER_CONTACT'
};

export default actionType;
