const actionType = {
  SET_CHATS: 'SET_CHATS',
  CLEAR_CHATS: 'CLEAR_CHATS',
  SET_CHAT_CONTENT: 'SET_CHAT_CONTENT',
  CLEAR_CHAT_CONTENT: 'CLEAR_CHAT_CONTENT',
  SET_SELECTED_USER_CHAT: 'SET_SELECTED_USER_CHAT',
  CLEAR_SELECTED_USER_CHAT: 'CLEAR_SELECTED_USER_CHAT'
};

export default actionType;
